freeboard/urls.py
from django.urls import path

from freeboard import views

app_name = 'freeboard'
urlpatterns = [

    path('', views.FreeBoardView.as_view(), name='freeboard_view'),
    path('insertfreeboard', views.InsertBoard_Random, name='insert_free_board'),
    path('jstest', views.JS_Test, name='jstest'),
]

js_board/urls.py
from django.contrib import admin
from django.urls import path, include

from js_board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('freeboard/', include('freeboard.urls')),
]

freeboard/models.py
from django.db import models

# Create your models here.
class Free_Board(models.Model):
    subject = models.CharField(max_length=50, null=False, blank=False)
    content = models.CharField(max_length=500, null=False, blank=False)
    createdDate = models.DateTimeField(max_length=50, null=False, blank=False, auto_now=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=False, default='')
    class Meta:
        db_table = 'free_board'

freeboard/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from freeboard.models import Free_Board



class FreeBoardView(TemplateView):
    template_name = 'freeboard/freeboardlist.html'
    def get_context_data(self, **kwargs):
        context = super(FreeBoardView, self).get_context_data(**kwargs)
        context['freeboard_list'] = Free_Board.objects.all()
        return context

def InsertBoard_Random(request):
    Free_Board.objects.create(subject="첫번째 글", content="반갑습니다.",
                              user_id=1)
    return render(request, 'home.html')

def JS_Test(request):
    myList = []

    return render(request, 'freeboard/js_test_view.html',{'mylist':myList})

js_board/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# 클래스 베이스 뷰
class HomeView(TemplateView):
    template_name = 'home.html'

# 함수 뷰
def Home(request):
    myList = ['동현', '지수']
    return render(request, 'home.html',{'mylist':myList})

templates/freeboard/freeboardlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Freeboard</title>
</head>
<body>
{% for board in freeboard_list %}
    제목 : {{  board.subject }}
    <br>
    내용 : {{  board.content }}
    <br>
{% endfor %}
</body>
</html>

templates/freeboard/js_test_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JS_TEST</title>
</head>
<body>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
안녕 ??

<br>
<p>리스트 표시</p>
{% for l in mylist %}
    {{ l }}
{% endfor %}
<br>
<a href="{% url 'freeboard:insert_free_board' %}">클릭</a>
<a href="{% url 'freeboard:freeboard_view' %}">자유게시판뷰</a>
<a href="{% url 'freeboard:jstest' %}">지수페이지</a>
</body>
</html>